{% set name = "arraykit" %}
{% set version = "1.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arraykit-{{ version }}.tar.gz
  sha256: c22d38998a30ac2a985792a1a2e50d426a84f35d18f002f1f029cfab708162e1

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - setuptools
    - python
    - pip
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - arraykit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/static-frame/arraykit
  summary: Array utilities for StaticFrame
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - flexatone
    - chaburkland
