{% set name = "arraykit" %}
{% set version = "0.1.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arraykit-{{ version }}.tar.gz
  sha256: 2180bbe76060f42bc750f9051b2b9079c2b1deb481d2ea10ab7bffc98562d343

build:
  number: 1
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - numpy >=1.17.4

test:
  imports:
    - arraykit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/InvestmentSystems/arraykit
  summary: Array utilities for StaticFrame
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - flexatone
    - brandtbucher
    - chaburkland
